/* eslint-disable no-console */
import * as fs from 'fs';
import * as path from 'path';

const ROOT_DIR = path.resolve(__dirname, '..');

// Helper to find the active phase ID and filename
function getActivePhaseInfo(): { id: string; file: string } {
  const indexPath = path.join(ROOT_DIR, 'docs/02-phases/phase-00-INDEX.md');
  if (!fs.existsSync(indexPath)) {
    return { id: '09', file: 'phase-09-sharing' };
  }
  const content = fs.readFileSync(indexPath, 'utf8');
  const lines = content.split('\n');
  for (const line of lines) {
    const match = line.match(/^-\s*\[\s*\]\s*\[\[02-phases\/([^|\]]+)(?:\|[^\]]+)?\]\]/);
    if (match) {
      const phaseFile = match[1]; // e.g. "phase-09-sharing"
      const phaseId = phaseFile.match(/phase-(\d+)/)?.[1] || '09';
      return { id: phaseId, file: phaseFile };
    }
  }
  return { id: '09', file: 'phase-09-sharing' };
}

// 1. Read phase spec (truncated to 3000 chars)
function getPhaseFileContent(phaseFile: string): string {
  const filePath = path.join(ROOT_DIR, `docs/02-phases/${phaseFile}.md`);
  if (fs.existsSync(filePath)) {
    return fs.readFileSync(filePath, 'utf8').substring(0, 3000);
  }
  return `Phase specification not found: docs/02-phases/${phaseFile}.md`;
}

// 2. Read recent debugging logs (last 3 modified < 7 days ago)
function getRecentDebugLogs(): string {
  const dirPath = path.join(ROOT_DIR, 'docs/06-debugging-journal');
  if (!fs.existsSync(dirPath)) {
    return 'No debugging journal directory found.';
  }

  const files = fs.readdirSync(dirPath).filter((f) => f.endsWith('.md'));
  const now = Date.now();
  const sevenDaysAgo = now - 7 * 24 * 60 * 60 * 1000;

  const fileInfos = files.map((file) => {
    const filePath = path.join(dirPath, file);
    const stats = fs.statSync(filePath);
    return { file, filePath, mtime: stats.mtimeMs };
  });

  // Filter for modified in last 7 days, sort descending by date, take top 3
  const recentFiles = fileInfos
    .filter((info) => info.mtime > sevenDaysAgo)
    .sort((a, b) => b.mtime - a.mtime)
    .slice(0, 3);

  if (recentFiles.length === 0) {
    return 'No debugging journal entries modified in the last 7 days.';
  }

  let concat = '';
  for (const f of recentFiles) {
    concat += `\n### Debugging Journal: ${f.file}\n`;
    concat += fs.readFileSync(f.filePath, 'utf8') + '\n';
  }
  return concat;
}

// 3. Read relevant architecture doc
function getArchitectureDoc(phaseId: string): string {
  const mapping: Record<string, string> = {
    '01': 'system-design.md',
    '02': 'auth-flow.md',
    '03': 'database-schema.md',
    '04': 'editor-toolbar-design.md',
    '05': 'socket-io-flow.md',
    '06': 'socket-io-flow.md',
    '07': 'crdt-design.md',
    '08': 'database-schema.md',
    '09': 'security-model.md',
    '10': 'system-design.md',
  };
  const docName = mapping[phaseId] || 'system-design.md';
  const docPath = path.join(ROOT_DIR, `docs/04-architecture/${docName}`);
  if (fs.existsSync(docPath)) {
    return fs.readFileSync(docPath, 'utf8');
  }
  return `Architecture document not found: docs/04-architecture/${docName}`;
}

function buildContext() {
  console.log('[Build AI Context] Compiling docs/ai-context.md...');

  // A. Read docs/PROJECT-STATUS.md
  const statusPath = path.join(ROOT_DIR, 'docs/PROJECT-STATUS.md');
  let projectStatus = '';
  if (fs.existsSync(statusPath)) {
    projectStatus = fs.readFileSync(statusPath, 'utf8');
  } else {
    projectStatus =
      '# Project Status\nPROJECT-STATUS.md not found. Please run npm run vault:sync first.\n';
  }

  // B. Get active phase info
  const phaseInfo = getActivePhaseInfo();
  const phaseContent = getPhaseFileContent(phaseInfo.file);

  // C. Read docs/03-daily-logs/current-day.md
  const dailyLogPath = path.join(ROOT_DIR, 'docs/03-daily-logs/current-day.md');
  let dailyLog = '';
  if (fs.existsSync(dailyLogPath)) {
    dailyLog = fs.readFileSync(dailyLogPath, 'utf8');
  } else {
    dailyLog = '# Daily Log\ncurrent-day.md not found.\n';
  }

  // D. Get recent debug logs
  const debugLogs = getRecentDebugLogs();

  // E. Get architecture doc
  const archDoc = getArchitectureDoc(phaseInfo.id);

  // F. Concatenate
  const aiContext = `<!-- AUTO-GENERATED BY scripts/build-ai-context.ts — DO NOT EDIT DIRECTLY -->
# CollabDoc AI Context System
> Combined context file for AI coding assistant sessions. Updated on ${new Date().toLocaleString()}.

---

## SECTION 1: PROJECT STATUS
${projectStatus}

---

## SECTION 2: CURRENT PHASE SPECIFICATION (TRUNCATED)
${phaseContent}

---

## SECTION 3: DAILY LOG
${dailyLog}

---

## SECTION 4: RECENT DEBUGGING JOURNAL
${debugLogs}

---

## SECTION 5: CURRENT PHASE ARCHITECTURE DOCUMENT
${archDoc}
`;

  const contextOutputPath = path.join(ROOT_DIR, 'docs/ai-context.md');
  fs.writeFileSync(contextOutputPath, aiContext, 'utf8');
  console.log(`[Build AI Context] Generated ${contextOutputPath} successfully.`);
}

buildContext();
